Update teams_notifcation.yml

diff --git a/.github/workflows/teams_notifcation.yml b/.github/workflows/teams_notifcation.yml
--- a/.github/workflows/teams_notifcation.yml
+++ b/.github/workflows/teams_notifcation.yml
@@ -14,6 +14,9 @@ jobs:
     runs-on: ubuntu-latest
     
     steps:
+      - name: Intentionally fail the job
+        run: exit 1 # This step will always fail
+
       - name: Send notification to Microsoft Teams
         run: |
           mention="<at>sreehass@amd.com</at>\n"
