Update teams_notifcation.yml

diff --git a/.github/workflows/teams_notifcation.yml b/.github/workflows/teams_notifcation.yml
--- a/.github/workflows/teams_notifcation.yml
+++ b/.github/workflows/teams_notifcation.yml
@@ -4,7 +4,7 @@ on:
   push:
     branches:
       - main
-  pull_request: 
+  pull_request:
     branches:
       - main
   workflow_dispatch: # Trigger to allow manual execution from GitHub Actions UI
@@ -17,7 +17,12 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
+      #- name: Simulate error
+      #  run: exit 1
+      #  id: error
+      
       - name: Get commit information
+        if: always()
         id: commit_info
         run: |
           COMMIT_HASH=$(git rev-parse HEAD)
@@ -41,8 +46,8 @@ jobs:
           # Get the build number
           BUILD_NUMBER="${{ github.run_number }}"
           
-          # Determine the job status
-          if [ -n "${{ failure() }}" ]; then
+          # Determine the job status based on the exit code of the previous step
+          if [ $? -ne 0 ]; then
             status="FAIL ❌"
             color="attention"
             mentionedId="${{ secrets.FAILURE_MENTION_ID }}"
