Update teams_notifcation.yml

diff --git a/.github/workflows/teams_notifcation.yml b/.github/workflows/teams_notifcation.yml
--- a/.github/workflows/teams_notifcation.yml
+++ b/.github/workflows/teams_notifcation.yml
@@ -14,9 +14,8 @@ jobs:
     runs-on: ubuntu-latest
     
     steps:
-      # Uncomment the following lines to simulate an error
       - name: Intentionally fail the job
-        run: exit 1 || true # This step will always fail
+        run: exit 1 || true # This step will always fail, but `|| true` ensures the workflow continues
         
       - name: Send notification to Microsoft Teams
         run: |
@@ -76,4 +75,3 @@ jobs:
           echo "$payload" | curl -X POST -H 'Content-Type: application/json' -d @- 'https://amdcloud.webhook.office.com/webhookb2/133d4f16-689b-4281-a94b-44725b948c77@3dd8961f-e488-4e60-8e11-a82d994e183d/IncomingWebhook/20c43fc799fd49e9813582813c638323/f9e22351-f1c9-494f-88c5-8e04accf2ffe'
     env:
       JOB_NAME: Build and Notify
- 
