Update teams_notifcation.yml

diff --git a/.github/workflows/teams_notifcation.yml b/.github/workflows/teams_notifcation.yml
--- a/.github/workflows/teams_notifcation.yml
+++ b/.github/workflows/teams_notifcation.yml
@@ -14,11 +14,10 @@ jobs:
     runs-on: ubuntu-latest
     
     steps:
-      #- name: Intentionally fail the job
-      #  run: exit 1 # This step will always fail
+      - name: Intentionally fail the job
+        run: exit 1 || true # This step will always fail
         
       - name: Send notification to Microsoft Teams
-        if: failure() # Send notification only if the previous step fails
         run: |
           mention="<at>sreehass@amd.com</at>\n"
           mentionedId="sreehass@amd.com"
