Update teams_notifcation.yml

diff --git a/.github/workflows/teams_notifcation.yml b/.github/workflows/teams_notifcation.yml
--- a/.github/workflows/teams_notifcation.yml
+++ b/.github/workflows/teams_notifcation.yml
@@ -14,11 +14,18 @@ jobs:
     runs-on: ubuntu-latest
     
     steps:
+      - name: Intentionally fail the job
+        run: exit 1 # This step will always fail
+        
       - name: Send notification to Microsoft Teams
+        if: failure() # Send notification only if the previous step fails
         run: |
           mention="<at>sreehass@amd.com</at>\n"
           mentionedId="sreehass@amd.com"
           mentionedName="A S S K, Sreeharsha"
+          
+          # Get the GitHub workflow run URL
+          BUILD_URL="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
           
           payload='{
             "type": "message",
@@ -31,17 +38,22 @@ jobs:
                     {
                       "type": "TextBlock",
                       "text": "'"$mention"'",
-                      "color": "good"
+                      "color": "attention"
                     },
                     {
                       "type": "TextBlock",
                       "text": "**Job Name:** '"$JOB_NAME"'",
-                      "color": "good"
+                      "color": "attention"
                     },
                     {
                       "type": "TextBlock",
-                      "text": "**Status:** PASS",
-                      "color": "good"
+                      "text": "**Status:** FAIL",
+                      "color": "attention"
+                    },
+                    {
+                      "type": "TextBlock",
+                      "text": "**Build URL:** [View Run]('"$BUILD_URL"')",
+                      "color": "attention"
                     }
                   ],
                   "msteams": {
@@ -62,3 +74,5 @@ jobs:
           }'
           
           echo "$payload" | curl -X POST -H 'Content-Type: application/json' -d @- 'https://amdcloud.webhook.office.com/webhookb2/133d4f16-689b-4281-a94b-44725b948c77@3dd8961f-e488-4e60-8e11-a82d994e183d/IncomingWebhook/20c43fc799fd49e9813582813c638323/f9e22351-f1c9-494f-88c5-8e04accf2ffe'
+    env:
+      JOB_NAME: Build and Notify
