Update teams_notifcation.yml

diff --git a/.github/workflows/teams_notifcation.yml b/.github/workflows/teams_notifcation.yml
--- a/.github/workflows/teams_notifcation.yml
+++ b/.github/workflows/teams_notifcation.yml
@@ -16,7 +16,7 @@ jobs:
     steps:
       # Uncomment the following lines to simulate an error
       - name: Intentionally fail the job
-        run: exit 1 # This step will always fail
+        run: exit 1 || true # This step will always fail
         
       - name: Send notification to Microsoft Teams
         run: |
