Update teams_notifcation.yml

diff --git a/.github/workflows/teams_notifcation.yml b/.github/workflows/teams_notifcation.yml
--- a/.github/workflows/teams_notifcation.yml
+++ b/.github/workflows/teams_notifcation.yml
@@ -17,18 +17,9 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Simulate error
-        run: exit 1
-        id: error
-      
-      - name: Get commit information
-        id: commit
-        run: |
-          COMMIT_HASH=$(git rev-parse HEAD)
-          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
-          
-          echo "::set-output name=commit_hash::$COMMIT_HASH"
-          echo "::set-output name=branch_name::$BRANCH_NAME"
+      #- name: Simulate error
+      #  run: exit 1
+      #  id: error
       
       - name: Send notification to Microsoft Teams
         if: always()
@@ -37,8 +28,8 @@ jobs:
           JOB_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
           
           # Get the commit information
-          COMMIT_HASH=$(echo "${{ steps.commit.outputs.commit_hash }}")
-          BRANCH_NAME=$(echo "${{ steps.commit.outputs.branch_name }}")
+          COMMIT_HASH=$(git rev-parse HEAD)
+          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
           
           # Get the repository URL
           REPO_URL="[${{ github.event.repository.full_name }}](${{ github.event.repository.html_url }})"
@@ -52,6 +43,10 @@ jobs:
             color="attention"
             mentionedId="apinapak@amd.com"
             mentionedName="Pinapaka, Abhilash Sarath Teja"
+            
+            # If the job failed, branch name and latest commit information won't be available, so set them to empty
+            BRANCH_NAME=""
+            COMMIT_HASH=""
           else
             status="PASS ✅"
             color="good"
